apiVersion: v1
kind: Service
metadata:
  name: comment-nodeport-service
spec:
  type: NodePort
  selector:
    app: comments # find all the pod with label posts, which we define in `post-depl.yaml` file
  ports:
    - name: comments
      protocol: TCP
      port: 4001 # Node Port service port
      targetPort: 4001 # actual port that our application is listing for traffic on
      # port and targetPort may not be identical

