
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1 # number of Pods we want to create
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: rkteche/comment-service:latest  
---
apiVersion: v1
kind: Service
metadata:
  name: comments-cluster-srv
spec:
  # If not define then K8s will automatically create ClusterIP service
  selector:
    app: comments # find all the pod with label comments, which we define in `post-depl.yaml` file
  ports:
    - name: comments
      protocol: TCP
      port: 4001 # Node Port service port
      targetPort: 4001 # actual port that our application is listing for traffic on
      # port and targetPort may not be identical