apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # find all the pod with label posts, which we define in `post-depl.yaml` file
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # Node Port service port
      targetPort: 4000 # actual port that our application is listing for traffic on
      # port and targetPort may not be identical

