apiVersion: v1
kind: Service
metadata:
  name: query-nodeport-service
spec:
  type: NodePort
  selector:
    app: query # find all the pod with label posts, which we define in `post-depl.yaml` file
  ports:
    - name: query
      protocol: TCP
      port: 4002 # Node Port service port
      targetPort: 4002 # actual port that our application is listing for traffic on
      # port and targetPort may not be identical

